Department-for-Transport-Disruptions/create-disruptions-data

package-lock.json
package.json
packages/siri-sx-generator/index.ts
packages/siri-sx-generator/package-lock.json
packages/siri-sx-generator/package.json
stacks/SiriGeneratorStack.ts

Node.js lambda (written in TypeScript) created which parses and prints the contents of an S3 bucket after a file is uploaded to the bucket
Upload a file to s3 (cdd-disruptions-json) and check logs to see if the lambda (cddsirigenerator) was triggered and the contents should print on your terminal

feat: Setup initial SIRI-SX Generator Lambda

---

.github/workflows/pr-merged.yml
package-lock.json
site/constants/index.ts
site/package.json
site/pages/__snapshots__/contact.test.tsx.snap
site/pages/api/feedback.api.ts
site/pages/api/feedback.test.ts
site/utils/apiUtils/feedbackEmailer.ts
stacks/SiteStack.ts

Access the /feedback page and fill the form. Click submit. Logger should log the data for local and for test the email should be sent to [feedback@dft-create-data.com](mailto:feedback@dft-create-data.com)

Feedback emailer configured using SES

---

site/pages/__snapshots__/create-consequence-network.test.tsx.snap
site/pages/__snapshots__/create-consequence-operator.test.tsx.snap
site/pages/api/create-consequence-network.test.ts
site/pages/api/create-consequence-operator.test.ts
site/pages/api/publish.test.ts
site/pages/create-consequence-network.page.tsx
site/pages/create-consequence-network.test.tsx
site/pages/create-consequence-operator.page.tsx
site/pages/create-consequence-operator.test.tsx
site/pages/review-disruption.test.tsx
site/schemas/consequence.schema.ts
site/testData/mockData.ts
site/utils/index.test.ts

Access pages using the below path
`/create-consequence-network`
`/create-consequence-operator`

Headers update for consequence network and operator page

---

site/pages/create-consequence-services/[disruptionId]/[consequenceIndex].page.tsx
site/pages/create-consequence-stops/[disruptionId]/[consequenceIndex].page.tsx

The stops dropdown was not allowing a user to search and click for a stop

bugfix: Fixing stops dropdown

---

site/pages/create-consequence-network/[disruptionId]/[consequenceIndex].page.tsx
site/pages/create-consequence-network/__snapshots__/create-consequence-network.test.tsx.snap
site/pages/create-consequence-operator/[disruptionId]/[consequenceIndex].page.tsx
site/pages/create-consequence-operator/__snapshots__/create-consequence-operator.test.tsx.snap
site/pages/create-consequence-services/[disruptionId]/[consequenceIndex].page.tsx
site/pages/create-consequence-services/__snapshots__/create-consequence-services.test.tsx.snap
site/pages/create-consequence-stops/[disruptionId]/[consequenceIndex].page.tsx
site/pages/create-consequence-stops/__snapshots__/create-consequence-stops.test.tsx.snap

Click the change button on each of the consequence type pages - should not error

fix: Change Consequence type

---

.eslintrc
site/components/map/Map.tsx
site/components/map/MapControls.tsx
site/components/map/ServicesMap.tsx
site/components/map/StopsMap.tsx
site/data/refDataApi.ts
site/pages/_document.page.tsx
site/pages/create-consequence-operator/[disruptionId]/[consequenceIndex].page.tsx
site/pages/create-consequence-services/[disruptionId]/[consequenceIndex].page.tsx
site/pages/create-consequence-stops/[disruptionId]/[consequenceIndex].page.tsx
site/schemas/consequence.schema.ts
site/styles/globals.scss
stacks/SiteStack.ts

Includes DISRUPTION-113 tooltip: unselected stops within polygon

feat:  Services polygon

---

site/constants/index.ts
site/pages/__snapshots__/login.test.tsx.snap
site/pages/api/login.api.ts
site/pages/api/login.test.ts
site/pages/login.page.tsx
site/pages/login.test.tsx
site/schemas/login.schema.ts
site/utils/formUtils.ts

UI changes for login page 

---

site/pages/type-of-consequence/[disruptionId]/[consequenceIndex].page.tsx
site/pages/type-of-consequence/__snapshots__/type-of-consequence.test.tsx.snap

updated page title to "Add a consequence" title in all pages where applicable

Fix for irregular add consequence title

---

site/pages/__snapshots__/account-settings.test.tsx.snap
site/pages/account-settings.page.tsx
site/pages/account-settings.test.tsx

Access the account settings page to view the admin area codes

Changes to display admin area code for the org

---

site/constants/index.ts
site/middleware.api.ts
site/pages/__snapshots__/expired-link.test.tsx.snap
site/pages/api/register.api.ts
site/pages/expired-link.page.tsx
site/pages/expired-link.test.tsx

Create a new user using cli-helpers create-user command. A registration link is sent to the users email id. Once it is past the expired duration click the link and it should navigate the user to appropriate error message page

Message to be displayed to user when an expired registration link is clicked

---

site/components/form/SearchSelect.tsx
site/constants/index.ts
site/data/dynamo.ts
site/data/refDataApi.ts
site/middleware.api.ts
site/pages/api/sysadmin/delete-org.api.ts
site/pages/api/sysadmin/org.api.ts
site/pages/api/sysadmin/org.test.ts
site/pages/api/sysadmin/users.test.ts
site/pages/sysadmin/__snapshots__/manage-organisations.test.tsx.snap
site/pages/sysadmin/__snapshots__/org.test.tsx.snap
site/pages/sysadmin/manage-organisations.page.tsx
site/pages/sysadmin/org.page.tsx
site/pages/sysadmin/org.test.tsx
site/schemas/organisation.schema.ts
site/tailwind.config.js
stacks/SiteStack.ts

Testing instructions:
Login as system admin and then click on Edit link/ Add organisation in Manage organisations page

changes for managing orgs and additional fixes

---

site/pages/api/admin/delete-user.api.ts
site/pages/api/admin/delete-user.test.ts

Go to user management and delete yourself - you should be logged out and your user deleted - so when you try to login you should be unable to

fix: When deleting yourself sign out

---

site/pages/api/admin/resend-invite.api.ts
site/pages/api/admin/resend-invite.test.ts
site/pages/api/sysadmin/users.api.ts

Below the fixes in the code
- Issue for routing to error page when an existing user email id is added when adding admin users
- Issue for routing to error page when resend invite is clicked for active user

Fix for issues with users  system admin panel

---

site/data/dynamo.ts
site/data/hootsuite.ts
site/data/s3.ts
site/pages/admin/social-media-accounts.page.tsx
site/pages/api/hootsuite-callback.api.ts
site/pages/api/hootsuite-callback.test.ts
site/pages/api/publish-edit.api.ts
site/pages/api/publish-edit.test.ts
site/pages/api/publish.api.ts
site/pages/api/publish.test.ts
site/pages/create-social-media-post/[disruptionId]/[socialMediaPostIndex].page.tsx
site/pages/dashboard.page.tsx
site/utils/apiUtils/index.test.ts
site/utils/apiUtils/index.ts

try connect to the hootsuite account twice it will throw an error second time
added try catch for the refresh token issue

fix: fixed duplicate connection issue and added try catch to understand error

---

site/components/form/TextInput.tsx
site/interfaces/index.ts
site/pages/create-consequence-network/[disruptionId]/[consequenceIndex].page.tsx
site/pages/create-consequence-network/__snapshots__/create-consequence-network.test.tsx.snap
site/pages/create-consequence-network/create-consequence-network.test.tsx
site/pages/create-consequence-operator/[disruptionId]/[consequenceIndex].page.tsx
site/pages/create-consequence-operator/__snapshots__/create-consequence-operator.test.tsx.snap
site/pages/create-consequence-operator/create-consequence-operator.test.tsx
site/pages/create-consequence-services/[disruptionId]/[consequenceIndex].page.tsx
site/pages/create-consequence-services/__snapshots__/create-consequence-services.test.tsx.snap
site/pages/create-consequence-services/create-consequence-services.test.tsx
site/pages/create-consequence-stops/[disruptionId]/[consequenceIndex].page.tsx
site/pages/create-consequence-stops/__snapshots__/create-consequence-stops.test.tsx.snap
site/pages/create-consequence-stops/create-consequence-stops.test.tsx

added copy buttons to consequence pages

feat: Copy disruption summary consequences

---

site/pages/api/hootsuite-callback.api.ts
site/pages/api/hootsuite-callback.test.ts

- Login as org admin and access the Social media page. Connect to hootsuite should display the details about successful hootsuite connection

Fix for the logout issue with incompatible lambda edge runtime for node:crypto module

---

site/pages/admin/social-media-accounts.page.tsx
site/pages/admin/social-media-accounts.test.tsx
site/pages/disruption-detail/[disruptionId].page.tsx
site/pages/disruption-detail/disruption-detail.test.tsx

To test change the code so it is STAGE !== 'aj' (your stage) and then see how the connect to hootsuite and add a social media post does not show

chore: feature flag social media

---

site/pages/disruption-detail/[disruptionId].page.tsx

fix to hide social media button when feature is disabled

fix to hide social media button when feature is disabled

---

site/data/refDataApi.ts

Fix for admin area code api endpoint

Fix for admin area code api endpoint

---

site/pages/api/duplicate-disruption.api.ts
site/pages/api/duplicate-disruption.test.ts
site/pages/disruption-detail/[disruptionId].page.tsx
site/pages/disruption-detail/__snapshots__/disruption-detail.test.tsx.snap
site/pages/review-disruption/[disruptionId].page.tsx
site/pages/review-disruption/__snapshots__/review-disruption.test.tsx.snap

- social media posts cannot be duplicated 
- you can only duplicate a disruption when you are not editing

feat: Duplicate disruptions

---

site/pages/create-consequence-network/[disruptionId]/[consequenceIndex].page.tsx
site/pages/create-consequence-network/__snapshots__/create-consequence-network.test.tsx.snap
site/pages/create-consequence-operator/[disruptionId]/[consequenceIndex].page.tsx
site/pages/create-consequence-operator/__snapshots__/create-consequence-operator.test.tsx.snap
site/pages/create-consequence-services/[disruptionId]/[consequenceIndex].page.tsx
site/pages/create-consequence-services/__snapshots__/create-consequence-services.test.tsx.snap
site/pages/create-consequence-stops/[disruptionId]/[consequenceIndex].page.tsx
site/pages/create-consequence-stops/__snapshots__/create-consequence-stops.test.tsx.snap

Optional text added to non mandatory fields in create disruption and add consequence pages

Added optional text to required fields

---

site/pages/api/publish-edit.test.ts
site/pages/api/publish.test.ts
site/pages/api/reject.test.ts
site/pages/api/sysadmin/org.api.ts
site/pages/sysadmin/__snapshots__/org.test.tsx.snap
site/pages/sysadmin/org.page.tsx
site/schemas/organisation.schema.ts

The fix resolves the issue of datasource reverting to default value when a change is made to the organisation

Fix for issue with reverting the datasource to default when sys admin updates an org

---

site/utils/siri.ts

Remove blank space from org name in participantRef

Remove blank space from org name in participantRef

---

site/components/map/ServicesMap.tsx
site/components/map/StopsMap.tsx

To filter out stops in the polygon included in searched and selected. To add stops in the polygon to the hover function so they can show a pop up.

fix: tooltip selected stops 2

---

site/pages/api/admin/delete-user.api.ts
site/pages/api/admin/delete-user.test.ts

Removing the error that gets generated when your a sysadmin deleting a user from another org

fix: Remove deleting users restriction

---

site/components/layout/NotificationBanner.test.tsx
site/components/layout/NotificationBanner.tsx
site/components/layout/__snapshots__/NotificationBanner.test.tsx.snap
site/pages/api/duplicate-disruption.api.ts
site/pages/api/duplicate-disruption.test.ts
site/pages/review-disruption/[disruptionId].page.tsx
site/pages/review-disruption/__snapshots__/review-disruption.test.tsx.snap
site/pages/review-disruption/review-disruption.test.tsx

Go to an existing disruption and hit duplicate disruption and the banner should show then click publish or save as draft and navigate back to the duplicate there should be no banner

feat: Duplicate disruption - information banner

---

site/pages/forgot-password.page.tsx

removed schema field on text input to disable client side validation

fix to disable client side validation for reset password page

---

site/components/map/ServicesMap.tsx
site/components/map/StopsMap.tsx

Given I am creating a consequence
When I click select all when using the polygon tool 
Then I see a loading icon until it is loaded up

feat: Map loading icons

---

package-lock.json
site/components/map/DrawControl.tsx
site/components/map/MapControls.tsx
site/components/map/ServicesMap.tsx
site/components/map/StopsMap.tsx
site/package.json

Deleting the polygon should work in all cases on services and stops

fix: Polygon delete

---

site/components/map/ServicesMap.tsx
site/components/map/StopsMap.tsx
site/utils/mapUtils.ts

Warning message to be under the select all button

fix: Map error placement

---

site/data/dynamo.ts
site/pages/__snapshots__/dashboard.test.tsx.snap
site/pages/__snapshots__/view-all-social-media.test.tsx.snap
site/pages/dashboard.page.tsx
site/pages/review-disruption/[disruptionId].page.tsx
site/pages/view-all-social-media.page.tsx
site/pages/view-all-social-media.test.tsx
site/utils/dates.test.ts
site/utils/dates.ts

Navigate to the dashboard and click view all social media. You should either see a table or banner.
Three ways to test:
- Remove displayId from the disruption schema to show prior posts with social media (if you had some before the displayId change)
- Manually create data in dynamo db
- Use the dummy data in the test file

feat: View All Social Media

---

site/components/layout/PageNumbers.tsx
site/components/layout/__snapshots__/PageNumbers.test.tsx.snap
site/pages/__snapshots__/view-all-disruptions.test.tsx.snap

Go to view all disruptions and see pagination in the middle

fix: Center table Pagination

---

package-lock.json
site/pages/create-consequence-services/[disruptionId]/[consequenceIndex].page.tsx
site/pages/create-consequence-services/create-consequence-services.test.tsx

Updated services consequence functionality so that when a stop is selected from the dropdown menu, all services associated with that stop are added to the services dropdown.

feat: update to service consequence functionality

---

site/data/hootsuite.ts
site/data/twitter.ts
site/utils/apiUtils/index.ts

Try posting multiple social media posts

fix: Unable to successfully post more than 1 social media post

---

site/pages/__snapshots__/account-settings.test.tsx.snap
site/pages/account-settings.page.tsx
site/pages/account-settings.test.tsx
site/pages/admin/user-management.test.tsx
site/pages/api/admin/update-email-preference.api.ts
site/pages/api/login.test.ts
site/pages/api/update-email-preference.api.ts
site/pages/api/update-email-preference.test.ts
site/pages/sysadmin/users.test.tsx
site/schemas/session.schema.ts
site/schemas/user-management.schema.ts
site/testData/mockData.ts
site/utils/user.ts
stacks/CognitoStack.ts

Note: Might be worth waiting until ticket DISRUPTION-597 (notification emails for new roadworks) is completed before merging this PR.

feat:  street manager notification email settings

---

packages/roadworks-notifier/cancelledNotifier.ts
packages/roadworks-notifier/newNotifier.ts

add logger message to roadwork notifications, update urls in the email to remove an  extra slash

chore: roadworks notification logger message

---

site/components/ReviewConsequenceTable.tsx
site/pages/disruption-detail/[disruptionId].page.tsx
site/pages/disruption-detail/__snapshots__/disruption-detail.test.tsx.snap
site/pages/disruption-detail/disruption-detail.test.tsx
site/pages/review-disruption/[disruptionId].page.tsx
site/pages/review-disruption/__snapshots__/review-disruption.test.tsx.snap
site/pages/review-disruption/review-disruption.test.tsx

https://github.com/Department-for-Transport-Disruptions/create-disruptions-data/pull/455 to be reviewed first

feat: Disruptions detail and review page for cancellations

---

site/pages/__snapshots__/dashboard.test.tsx.snap
site/pages/dashboard.page.tsx
site/pages/disruption-detail/[disruptionId].page.tsx
site/pages/disruption-detail/__snapshots__/disruption-detail.test.tsx.snap

EXPECTED
The purpose of this Success Criterion is to ensure a keyboard focus indicator is clearly visible and discernible. Focus Appearance is closely related to [2.4.7 Focus Visible](https://www.w3.org/WAI/WCAG22/Understanding/focus-visible.html) and [1.4.11 Non-text Contrast](https://www.w3.org/WAI/WCAG22/Understanding/non-text-contrast.html). Focus Visible requires that a visible focus indicator exists while a component has keyboard focus; Focus Appearance defines a minimum level of visibility. Where Non-text Contrast requires a component to have adequate contrast against the background in each of its states, Focus Appearance requires sufficient contrast for the focus indicator itself.
in plain English: it should be clear where keyboard focus is at all times

fix: Focus lost on dashboard

---

site/components/ViewAllContents.tsx

Refactored filter logic because with the old code, the operator and search text filters were being ignored as the status filter was causing the .filter() to return early.
Ticket: https://kpmgengineering.atlassian.net/browse/DISRUPTION-820

fix: Refactor filter logic on view all disruptions page

---

stacks/QueueStack.ts

Add Roadworks queue function to VPC to allow it to write to the DB.

fix: Add roadworks queue function to vpc

---

packages/ref-data-service-api/utils/db.ts
shared-ts/db/migrations/1757083597_postgis_extension.mjs

- install postgis
- update stops polygon query

fix: ref data stops query with polygon query params
