site/pages/api/type-of-consequence.api.ts
site/pages/api/type-of-consequence.test.ts
site/pages/review-disruption/[disruptionId].page.tsx
site/pages/review-disruption/__snapshots__/review-disruption.test.tsx.snap
site/pages/type-of-consequence/[disruptionId]/[consequenceIndex].page.tsx

Navigate to `/type-of-consequence` page and click save without choosing an option. Appropriate error should be displayed

Fix for issue with selecting consequence type page

---

site/pages/api/create-disruption.test.ts
site/schemas/create-disruption.schema.ts

Go to create-disruptions page and fill everything besides the publish end date/time - click submit and you should see the error as per the wireframes.

feat: UI refinement - missing publishing end date/time error handling

---

site/pages/api/create-social-media-post.api.ts
site/pages/api/create-social-media-post.test.ts

Show an error message when an error is triggered on the page and the user had uploaded an image before. It will prompt them to upload an image again

fix: Image lost on page refresh error

---

site/utils/dates.test.ts
site/utils/dates.ts

Click on the Create new disruptions link and enter the mandatory fields upto "when is this disruption?" section. In the said section enter only the start date for both disruption and publish fields. Do not enter the time and click save. Appropriate error message should be displayed instead of error page redirection

fix for error page redirection when start date is null

---

site/pages/api/create-social-media-post.api.ts
site/pages/disruption-detail/[disruptionId].page.tsx
site/pages/disruption-detail/__snapshots__/disruption-detail.test.tsx.snap
site/pages/review-disruption/[disruptionId].page.tsx
site/pages/review-disruption/__snapshots__/review-disruption.test.tsx.snap
site/utils/apiUtils/index.test.ts
site/utils/dates.ts

And if disruption is rejected but then editing it becomes pending so you can publish again
And on test the time for a post is scheduled one hour ahead of dev

fix: Remove change link on successful social media post

---

shared-ts/enums.ts
site/components/form/SearchSelect.tsx
site/components/map/ServicesMap.tsx
site/data/dynamo.ts
site/data/refDataApi.ts
site/interfaces/index.ts
site/pages/__snapshots__/account-settings.test.tsx.snap
site/pages/account-settings.page.tsx
site/pages/account-settings.test.tsx
site/pages/api/admin/update-org.api.ts
site/pages/api/admin/update-org.test.ts
site/pages/change-password.test.tsx
site/pages/create-consequence-services/[disruptionId]/[consequenceIndex].page.tsx
site/pages/create-consequence-services/create-consequence-services.test.tsx
site/pages/create-consequence-stops/create-consequence-stops.test.tsx
site/pages/dashboard.test.tsx
site/pages/sysadmin/manage-organisations.test.tsx
site/pages/sysadmin/users.test.tsx
site/pages/view-all-disruptions.page.tsx
site/schemas/consequence.schema.ts
site/schemas/organisation.schema.ts
site/schemas/session.schema.ts
site/testData/mockData.ts
site/utils/formUtils.ts

- Login as org admin user and then access the Account Settings page from top right corner. The radio buttons should be displayed only to org admins
- After the source data is clicked - navigate to consequence services page and observe that the services data changes based on the source for mode of transport
- The services dropdown in view  all disruptions page should display both tnds and bods data

Allow org admins to toggle source data between tnds and bods

---

site/components/OperatorSearch.test.tsx
site/components/OperatorSearch.tsx
site/components/ReviewConsequenceTable.tsx
site/pages/api/__snapshots__/delete-disruption.test.ts.snap
site/pages/api/__snapshots__/publish-edit.test.ts.snap
site/pages/api/__snapshots__/publish.test.ts.snap
site/pages/api/__snapshots__/reject.test.ts.snap
site/pages/api/create-consequence-operator.api.ts
site/pages/api/create-consequence-operator.test.ts
site/pages/create-consequence-operator/[disruptionId]/[consequenceIndex].page.tsx
site/pages/create-consequence-operator/__snapshots__/create-consequence-operator.test.tsx.snap
site/pages/create-consequence-operator/create-consequence-operator.test.tsx
site/pages/disruption-detail/[disruptionId].page.tsx
site/pages/disruption-detail/__snapshots__/disruption-detail.test.tsx.snap
site/pages/disruption-detail/disruption-detail.test.tsx
site/pages/review-disruption/[disruptionId].page.tsx
site/pages/review-disruption/__snapshots__/review-disruption.test.tsx.snap
site/pages/review-disruption/review-disruption.test.tsx
site/pages/view-all-disruptions.page.tsx
site/schemas/consequence.schema.ts
site/testData/mockData.ts
site/utils/formUtils.ts
site/utils/index.test.ts
site/utils/siri.ts

- Create new disruptions or update existing disruptions with consequences of type operators. Publish the disruptions
- Pull the Siri SX XML using the API which should contain <OperatorName/> field for consequences with type Operators

Add OperatorName field to Siri SX for consequences of type operator

---

site/components/form/DateSelector.tsx
site/components/form/TimeSelector.tsx
site/components/form/__snapshots__/TimeSelector.test.tsx.snap
site/pages/create-consequence-network/__snapshots__/create-consequence-network.test.tsx.snap
site/pages/create-consequence-operator/__snapshots__/create-consequence-operator.test.tsx.snap
site/pages/create-consequence-services/__snapshots__/create-consequence-services.test.tsx.snap
site/pages/create-consequence-stops/__snapshots__/create-consequence-stops.test.tsx.snap
site/pages/create-disruption/[disruptionId].page.tsx
site/pages/create-disruption/__snapshots__/create-disruption.test.tsx.snap
site/pages/create-social-media-post/[disruptionId]/__snapshots__/create-social-media-post.test.tsx.snap

To test:
Go to the create disruption page and then scroll to publication date and time
As per wireframes should be a 'Now' button click on it to see the current date and time

feat: Now button on create disruption page

---

site/pages/api/__snapshots__/publish-edit.test.ts.snap
site/pages/api/__snapshots__/publish.test.ts.snap
site/pages/api/__snapshots__/reject.test.ts.snap
site/testData/mockData.ts
site/utils/siri.ts

- Create new disruptions or edit existing disruptions with network wide and operator wide consequences. Publish this disruptions and view the Siri SX xml which should have the additional fields.

Added additional fields in siri xml for stops and networks type consequences

---

site/components/ReviewConsequenceTable.tsx
site/pages/create-disruption/[disruptionId].page.tsx
site/pages/create-disruption/__snapshots__/create-disruption.test.tsx.snap

- Click create new disruption link and select validity date fields. This should update respective fields in publish disruption

Changes to mirror publish date fields when validity fields are entered

---

site/pages/api/duplicate-disruption.api.ts
site/pages/api/duplicate-disruption.test.ts
site/pages/disruption-detail/[disruptionId].page.tsx
site/pages/disruption-detail/__snapshots__/disruption-detail.test.tsx.snap
site/pages/review-disruption/[disruptionId].page.tsx
site/pages/review-disruption/__snapshots__/review-disruption.test.tsx.snap

Duplicate a disruption - then check if the display ids are different
Duplicate disruption button should only be shown when published status

fix: fixed duplicate display id issue

---

shared-ts/enums.ts
site/components/map/ServicesMap.tsx
site/data/refDataApi.ts
site/interfaces/index.ts
site/pages/account-settings.page.tsx
site/pages/create-consequence-operator/[disruptionId]/[consequenceIndex].page.tsx
site/pages/create-consequence-services/[disruptionId]/[consequenceIndex].page.tsx
site/pages/view-all-disruptions.page.tsx
site/schemas/organisation.schema.ts

Create service consequence page should now display tram services in drop down when vehicle mode is selected. This is extended to all other vehicle mode values.

Fix to display tram services in drop down

---

site/components/map/ServicesMap.tsx
site/components/map/StopsMap.tsx

To revert the changes done in https://github.com/Department-for-Transport-Disruptions/create-disruptions-data/pull/83/commits/4d59ee8cba8b7eed7d8798bee69e7fe4a113952a
To test it:
1.  Login and got to create / edit service consequences
2.  Click a mode e.g. Bus and then draw a polygon 
3.  Hover over a grey stop and it should have a tooltip

fix: Tooltip hover on unselected stop not working within polygon shape

---

site/components/map/ServicesMap.test.tsx
site/components/map/ServicesMap.tsx

a user shouldn't be able to use both the polygon shape and the services drop down at the same time
services/stops should be cleared when a polygon is drawn
when a service is selected from the dropdown and a polygon had already been drawn prior but not selected the selected services stops will be selected not the polygon's stops

fix: Polygon tool - Services 

---

site/components/map/ServicesMap.tsx
site/pages/create-consequence-services/[disruptionId]/[consequenceIndex].page.tsx
site/schemas/consequence.schema.ts

Navigate to adding consequences of type services. Select a stop type and then a service which has more than 100 stops. Click select all which should select all the stops and not limit it to 100

Fix to remove limit on selecting stops after choosing services

---

site/components/map/ServicesMap.tsx

Polygon tool does not work in "services" consequence page map (watch video evidence)
- Use codes 083, 107, 110, 146, 147
- Go to Manchester on the stops consequence page draw a similar sized polygon to the one in the bugfix ticket video
- Press back on the top left 
- Go to services consequence draw a similar polygon on the same area
- The loading icon should not stay there infinitely but it may take long to load the data about a minute or so

fix: Splicing AtcoCodes to prevent infinite loading

---

site/components/map/ServicesMap.tsx

When you go to the services consequence page and select services (with stops) and leave one in the dropdown - then click on a stop the warning shows. This is incorrect behaviour as the services with stops should allow you to select the stops and not show the warning message.
Logic has been fixed so only if there is a polygon does it check for services connected to the stop and show the warning if needed.

fix: Services with stops show warning message

---

site/components/ReviewConsequenceTable.tsx
site/components/__snapshots__/ReviewConsequenceTable.test.tsx.snap
site/components/form/Table.tsx
site/components/form/__snapshots__/SearchSelect.test.tsx.snap
site/components/form/__snapshots__/Table.test.tsx.snap
site/components/layout/__snapshots__/Tabs.test.tsx.snap
site/pages/__snapshots__/account-settings.test.tsx.snap
site/pages/__snapshots__/change-password.test.tsx.snap
site/pages/__snapshots__/dashboard.test.tsx.snap
site/pages/__snapshots__/register.test.tsx.snap
site/pages/__snapshots__/reset-password.test.tsx.snap
site/pages/__snapshots__/view-all-disruptions.test.tsx.snap
site/pages/__snapshots__/view-all-social-media.test.tsx.snap
site/pages/admin/__snapshots__/add-user.test.tsx.snap
site/pages/admin/__snapshots__/social-media-accounts.test.tsx.snap
site/pages/admin/__snapshots__/user-management.test.tsx.snap
site/pages/create-consequence-network/__snapshots__/create-consequence-network.test.tsx.snap
site/pages/create-consequence-operator/__snapshots__/create-consequence-operator.test.tsx.snap
site/pages/create-consequence-services/__snapshots__/create-consequence-services.test.tsx.snap
site/pages/create-consequence-stops/__snapshots__/create-consequence-stops.test.tsx.snap
site/pages/create-disruption/__snapshots__/create-disruption.test.tsx.snap
site/pages/disruption-detail/[disruptionId].page.tsx
site/pages/disruption-detail/__snapshots__/disruption-detail.test.tsx.snap
site/pages/disruption-history/__snapshots__/disruption-history.test.tsx.snap
site/pages/review-disruption/[disruptionId].page.tsx
site/pages/review-disruption/__snapshots__/review-disruption.test.tsx.snap
site/pages/sysadmin/__snapshots__/manage-organisations.test.tsx.snap
site/pages/sysadmin/__snapshots__/org.test.tsx.snap
site/pages/sysadmin/__snapshots__/users.test.tsx.snap
site/tailwind.config.js

The fix ensures that the change link column in disruption details and review disruption page are aligned as expected.

Fix to align change links column

---

site/pages/create-disruption/[disruptionId].page.tsx

Currently when the create disruption page is submitted without data in publication fields, the reloaded page with errors has data populated in these fields. The fix ensures that these fields are empty when there is an error

Fix to not auto display publication fields when there is an error on the field

---

site/data/cognito.ts
site/pages/admin/user-management.page.tsx
site/pages/sysadmin/__snapshots__/users.test.tsx.snap
site/pages/sysadmin/users.page.tsx
site/pages/sysadmin/users.test.tsx
site/schemas/user-management.schema.ts
site/utils/tableUtils.ts

Added functionality for system admins to be able to view all user types for a given organisation. System admins should be able to remove all user types, but can only resend invites to org admins. 
System admins should be able to view other system admins, but not perform any actions.

feat: sys admin view all users

---

site/components/ReviewConsequenceTable.tsx
site/pages/api/create-consequence-network.api.ts
site/pages/api/create-consequence-operator.api.ts
site/pages/api/create-consequence-services.api.ts
site/pages/api/create-consequence-stops.api.ts
site/pages/api/create-disruption.api.ts
site/pages/api/create-disruption.test.ts
site/pages/create-consequence-network/[disruptionId]/[consequenceIndex].page.tsx
site/pages/create-consequence-network/__snapshots__/create-consequence-network.test.tsx.snap
site/pages/create-consequence-operator/[disruptionId]/[consequenceIndex].page.tsx
site/pages/create-consequence-operator/__snapshots__/create-consequence-operator.test.tsx.snap
site/pages/create-consequence-services/[disruptionId]/[consequenceIndex].page.tsx
site/pages/create-consequence-services/__snapshots__/create-consequence-services.test.tsx.snap
site/pages/create-consequence-stops/[disruptionId]/[consequenceIndex].page.tsx
site/pages/create-consequence-stops/__snapshots__/create-consequence-stops.test.tsx.snap
site/pages/disruption-detail/[disruptionId].page.tsx
site/pages/disruption-detail/__snapshots__/disruption-detail.test.tsx.snap
site/pages/review-disruption/[disruptionId].page.tsx
site/pages/review-disruption/__snapshots__/review-disruption.test.tsx.snap
site/pages/type-of-consequence/[disruptionId]/[consequenceIndex].page.tsx
site/utils/formUtils.ts

The issue was that if you go to an existing template and attempt to change something it would error.
The fix is to check whether the template is in edit or create flow and then redirect accordingly.
Test the create flows and the edit flows.
Also fixes Error page found when changing the selected consequence during creating a new template

fix: Error page found when change link is selected on existing template

---

site/pages/disruption-detail/[disruptionId].page.tsx
site/pages/disruption-detail/disruption-detail.test.tsx

Go to view all templates
Click a draft template (or create one)
You should see the create disruption button click on it and go through the flow or click to the main dashboard
See if the disruption appears as draft/published

feat: Add "Create disruption" functionality to draft templates

---

site/constants/index.ts
site/pages/create-consequence-network/[disruptionId]/[consequenceIndex].page.tsx
site/pages/create-consequence-operator/[disruptionId]/[consequenceIndex].page.tsx
site/pages/create-consequence-services/[disruptionId]/[consequenceIndex].page.tsx
site/pages/create-consequence-stops/[disruptionId]/[consequenceIndex].page.tsx
site/pages/disruption-detail/[disruptionId].page.tsx
site/pages/disruption-not-found.page.tsx
site/pages/review-disruption/[disruptionId].page.tsx
site/pages/type-of-consequence/[disruptionId]/[consequenceIndex].page.tsx

View a template or disruption, delete it press back arrow on the browser.
Chris has stated he wants both to navigate back to the dashboard. Design of page has been confirmed with him too.

fix: Adding error messages for templates and disruptions not found

---

package-lock.json
packages/organisations-api/get-organisation-stops/index.ts
shared-ts/disruptionTypes.ts
shared-ts/organisationTypes.ts
shared-ts/package.json
shared-ts/utils/dynamo.ts
shared-ts/utils/index.ts
shared-ts/utils/refDataApi.ts
site/components/map/ServicesMap.tsx
site/data/refDataApi.ts
site/pages/create-consequence-services/[disruptionId]/[consequenceIndex].page.tsx
site/schemas/consequence.schema.ts
stacks/services/APIGateway.ts

Testing instruction:
Run "npm run dev" from root and then run the below command to invoke and test the api. Update values according to your local env setup
```curl -X GET -H "x-api-key: <your-api-key>" https://<api-gateway-endpoint>/<sst-stage-name>/organisations/<org-id>/impacted/stops```
example:
```curl -X GET -H "x-api-key: <api-key>" https://taejenagw7.execute-api.eu-west-2.amazonaws.com/kalva1/organisations/2c759a03-b961-43e2-9a47-db9a894dfe91/impacted/stops```

changes to retrieve disruption stops and routes for services in an organisation

---

stacks/SiteStack.ts

After looking at logs:
{"level":"error","message":"Failed to retrieve group for user"}
'no identity-based policy allows the cognito-idp:AdminListGroupsForUser action' fixing this error

fix: "Edit" link within the user management page does not work

---

site/components/ViewAllContents.tsx
site/pages/api/get-all-disruptions.api.ts
site/pages/api/publish.api.ts
site/pages/dashboard.page.tsx
site/pages/view-all-templates.page.tsx

- Removed template link from dashboard for operator users
- Added redirect on the "view-all-templates" page for operator users (goes to 404)
- Added guard in "get-all-disruptions" api to return an empty object if operator user tries to retrieve template info
- Added guard to "publish" api so that operators cannot publish a template

feat: remove template features for operator users

---

cli-helpers/README.md
site/data/nextdoor.ts
site/pages/api/create-social-media-post.api.ts
site/pages/create-social-media-post/[disruptionId]/[socialMediaPostIndex].page.tsx
site/pages/disruption-detail/[disruptionId].page.tsx
site/pages/review-disruption/[disruptionId].page.tsx
site/pages/view-all-social-media.page.tsx
site/schemas/nextdoor.schema.ts
site/schemas/social-media.schema.ts

Small refactor to:
- format the body in the create-social-media.api.ts file
- updated nextdoor post schema for area boundary to be optional
- update wording of groupIds to nextdoorAgencyBoundaries
- change agency boundary dropdown to not include selected boundaries in the dropdown options

Nextdoor backend refactor

---

packages/roadworks-notifier/cancelledNotifier.test.ts
packages/roadworks-notifier/cancelledNotifier.ts
packages/roadworks-notifier/newNotifier.test.ts
packages/roadworks-notifier/newNotifier.ts
shared-ts/utils/index.ts

Bug found when testing the cancelled roadwork notification. SES cannot send emails to more than 50 users at once. This PR is to batch emails into groups of 50 for both cancelled and new roadworks notifications - updated tests accordingly.

fix: batch emails for roadworks notifiers

---

site/components/page-templates/UserDetailPageTemplate.tsx

The empty string was being stringified with multiple clicks of the submit button. This simple check means if there is no operator in the state do not stringify it.
To test:
Go to add user and then select operator, click submit, wait and click submit again - the error message should be correct.

fix: Incorrect error message displayed when creating a new operator

---

site/components/map/ServicesMap.tsx
site/components/map/StopsMap.tsx
site/data/refDataApi.ts
site/pages/create-consequence-journeys/[disruptionId]/[consequenceIndex].page.tsx
site/pages/create-consequence-services/[disruptionId]/[consequenceIndex].page.tsx
site/pages/create-consequence-stops/[disruptionId]/[consequenceIndex].page.tsx
site/utils/formUtils.test.ts
site/utils/formUtils.ts
site/utils/index.test.ts
site/utils/index.ts

- update calls to ref data service to include additional stop types BCS and BCQ (inc coaches)
- remove busStopTypes as queryParam to ref data service

feat: BODS-819 allow additional naptan stop types 

---

pnpm-lock.yaml
site/components/layout/CookieBanner.tsx
site/components/layout/__snapshots__/CookieBanner.test.tsx.snap
site/package.json

includes fix for cookier banner

chore: update govuk-frontend to 5.11

---

.sst/types/index.ts
packages/txc-uploader/tests/test_txc_uploader.py
packages/txc-uploader/txc_processor.py
stacks/RefDataStepFunctionStack.ts

We are in the process of migrating the reference data service to this repo.
This PR copies over the following changes that were completed in the reference data service:
- handle missing long/lat data
- memory bump to the tnds retriever lambda to handle increase in TNDS data
- allow for a small number of failures for processing of TXC data (this was added due to BODS providing a small number (~5) empty zips, in this case we still want to continue to step function and process the rest of the TXC data)

fix: Handle missing long lat in txc uploader

---

stacks/RoadworksNotificationStack.ts
stacks/SiriAPIStack.ts
stacks/SiriGeneratorStack.ts
stacks/SiteStack.ts
stacks/utils/index.ts

Disable the prod site and functions (e.g. SIRI-SX generator and Roadworks Notifier) from using the new disruptions ref data API url. 
This is to unblock releases of other features whilst testing of the new disruptions ref data migration occurs on lower environments.

chore: Disable ref data migration changes for prod site and functions
